/*	File chi_test.cpp

Authors: J. Koch, M. Dausmann

This is the main program to solve the following exercise:
proove the quality of the first 50 digits taken as random numbers.

Reference: Chapter Random Numbers

*/
#include <iostream>
using namespace std;

#ifdef __linux__
#define TheEnd 
#else
#define TheEnd getchar();getchar()
#endif

extern void execExampleStandardNumbers();
extern void execExerciseDigitsOfPI();

//<-chi_square--
double chiSquareOf(int H[], double p[], const int n, const int N)
{
	double sum = 0.0, chi;
	for (int i = 0; i < N; i++) {
		chi = (H[i] - (n * p[i])) * (H[i] - (n * p[i]));
		chi = chi / (n * p[i]);
		sum = sum + chi;
	}
	return sum;
}
//--chi_square->

int main() {
	cout << "Proof of quality of random numbers using chi^2-test" << endl;
	cout << "===================================================" << endl;
	int what = 0;
	cout << endl;
	cout << "What random numbers shall be tested?" << endl;
	cout << "1: Digits of PI as random numbers (exercise)" << endl;
	cout << "2: Standard random numbers generated by a LCG (example)" << endl;
	cin >> what;
	if (what == 2) execExampleStandardNumbers();
	else execExerciseDigitsOfPI();

	TheEnd;
	return 0;
}
