/*	File execute_example.cpp

Authors: J. Koch, M. Dausmann

This is the function to compute the figures of
the example in the sriptum: 
proove the quality of standard random numbers
generated by a certain LCG.

Reference: Chapter Random Numbers

*/
#include <iostream>
#include <iomanip>
#include "standard_numbers.hpp"
#include "standard_intervals.hpp"
#include "standard_squares.hpp"
using namespace std;

extern double chiSquareOf(int h[], double p[], const int n, const int N);

void execExampleStandardNumbers() {
	StandardNumbers numbers;
	cout << endl;
	cout << "Distribution of numbers into intervals" << endl;
	StandardIntervalDistribution iv_dist(numbers);
	iv_dist.getObservedDistribution();
	iv_dist.getExpectedProbalities();
	for (int i = 0; i < iv_dist.numberCategories; i++)
		cout << "Interval " << i + 1 << " = " << iv_dist.categories[i] << endl;
	cout << "Chi^2 of interval distribution: ";
	double chiIntervals =
		chiSquareOf(iv_dist.categories, iv_dist.probs, numbers.Max, iv_dist.numberCategories);
	cout << setprecision(6) << setfill('0');
	cout << chiIntervals << endl;
	cout << endl;

	cout << "Distribution of pairs into squares" << endl;
	StandardSquareDistribution sq_dist(numbers);
	sq_dist.getObservedDistribution();
	sq_dist.getExpectedProbalities();
	for (int i = 0; i < sq_dist.numberCategories; i++)
		cout << "Square " << i + 1 << " = " << sq_dist.categories[i] << endl;
	cout << "Chi^2 of square distribution: ";
	double chiQuadrants = 
    chiSquareOf(sq_dist.categories, sq_dist.probs, numbers.Max, sq_dist.numberCategories);
	cout << setprecision(6) << setfill('0');
	cout << chiQuadrants << endl << endl;
}
